#!/root/.local/share/pipx/venvs/aggregate6/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from aggregate6.aggregate6 import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
